# Generated by Django 3.2.3 on 2021-12-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='username')),
                ('email', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('fullName', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('isTFA', models.BooleanField(default=False)),
            ],
        ),
    ]
